name: Bug Report
description: Report a bug with the Pixie module
title: "[Bug] "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Module Version
      placeholder: "1.2"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android Version
      placeholder: "Android 13"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
